### ISSUE TITLE
How Can I Use This From The Command Line

### ISSUE THREAD

**Issue by mudgen** [samestep/boot-refresh#4]
I execute "boot repl watch refresh"  but then I don't have access to the repl anymore. Instead the following text gets displayed:

Starting file watcher (CTRL-C to quit)...

:reloading (ignition-project.core)
Elapsed time: 0.039 sec

The display is now only used to show when a file changes.  The repl is gone.  How do I get it back?
Is there a way I can use this from the command line?

**Comment by mudgen** [comment]
I think I understand this now -- I am not supposed to get the repl back, correct?  Instead I need to make a client repl connection to the repl server  and use that, correct?

**Comment by samestep** [comment]
That's correct. Specifically, you can start a REPL using `boot repl -s watch refresh` and then connect to it from a different terminal using `boot repl -c`.

**Comment by mudgen** [comment]
Okay, cool. Thank you.
